"""initial schema

Revision ID: 8add4a71d3d1
Revises: 
Create Date: 2026-03-03 11:07:30.713470
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8add4a71d3d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('civicplus_id', sa.Text(), nullable=False),
    sa.Column('url_date_slug', sa.Text(), nullable=False),
    sa.Column('agenda_url', sa.Text(), nullable=True),
    sa.Column('minutes_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('civicplus_id')
    )
    op.create_index(op.f('ix_meetings_date'), 'meetings', ['date'], unique=False)
    op.create_table('scrape_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('meetings_found', sa.Integer(), nullable=False),
    sa.Column('new_documents', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('pdf_hash', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_model', sa.Text(), nullable=True),
    sa.Column('summarized_at', sa.DateTime(), nullable=True),
    sa.Column('notified_email', sa.Boolean(), nullable=False),
    sa.Column('notified_bluesky', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('scrape_log')
    op.drop_index(op.f('ix_meetings_date'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
